Repository Jagroop2001/validify-string, pull requests merged in 2024-01, with the labels that each got.

#7 eslint file added
  src/.eslintrc.json
  src/utils/utilityFunctions.ts
Labels: JWOC, Medium

#9 Added/more utility features
  src/index.ts
  src/utils/utilityFunctions.ts
Labels: JWOC, Medium

#11 Valid IP Address
  src/index.ts
  src/utils/utilityFunctions.ts
Labels: JWOC, Easy

#18 added ishash, isalphanumeric, ishexadecimal fn
  Readme.md
  src/index.ts
  src/utils/utilityFunctions.ts
Labels: JWOC, Hard

#21 Adding Functionality of checking is string contains only ascii characters
  Readme.md
  src/index.ts
  src/utils/utilityFunctions.ts
Labels: JWOC, Easy

#22 Add below mentioned validators : 1 #15
  Readme.md
  src/index.ts
  src/utils/validateFunctions.ts
Labels: JWOC, Hard
